using Microsoft.Extensions.Logging;
using Azure.Communication.Email;
using Chivato.Shared.Models;
using System.Text;

namespace Chivato.Shared.Services;

public class EmailService : IEmailService
{
    private readonly ILogger<EmailService> _logger;

    public EmailService(ILogger<EmailService> logger)
    {
        _logger = logger;
    }

    public async Task SendDriftReportAsync(
        IEnumerable<string> recipients,
        string pipelineName,
        IEnumerable<DriftRecordEntity> driftRecords,
        string connectionString,
        string fromEmail,
        string? fromDisplayName = null,
        CancellationToken cancellationToken = default)
    {
        if (!driftRecords.Any())
        {
            _logger.LogInformation("No drift records to report, skipping email");
            return;
        }

        if (!recipients.Any())
        {
            _logger.LogWarning("No recipients configured for drift report");
            return;
        }

        try
        {
            var client = new EmailClient(connectionString);

            var subject = $"Drift Detected: {pipelineName} - {driftRecords.Count()} items";
            var htmlBody = GenerateDriftReportHtml(pipelineName, driftRecords);
            var plainBody = GenerateDriftReportPlainText(pipelineName, driftRecords);

            var emailRecipients = new EmailRecipients(
                recipients.Select(r => new EmailAddress(r)).ToList());

            var emailContent = new EmailContent(subject)
            {
                Html = htmlBody,
                PlainText = plainBody
            };

            var emailSender = new EmailAddress(fromEmail, fromDisplayName ?? "Chivato Drift Monitor");
            
            // Note: Azure SDK allows sender address as string, but here we want to ensure format.
            // Actually, the simpler SendAsync method takes senderAddress as string.
            
            var emailMessage = new EmailMessage(
                senderAddress: fromEmail,
                recipients: emailRecipients,
                content: emailContent);

            var operation = await client.SendAsync(Azure.WaitUntil.Completed, emailMessage, cancellationToken);

            _logger.LogInformation(
                "Drift report sent to {RecipientCount} recipients. Operation ID: {OperationId}",
                recipients.Count(), operation.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to send drift report email");
            // We don't throw here to avoid failing the whole processing flow just for email
        }
    }

    private string GenerateDriftReportHtml(string pipelineName, IEnumerable<DriftRecordEntity> driftRecords)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html><head><style>");
        sb.AppendLine("body { font-family: Arial, sans-serif; }");
        sb.AppendLine(".drift-item { border: 1px solid #ccc; padding: 10px; margin-bottom: 10px; border-radius: 5px; }");
        sb.AppendLine(".severity-HIGH { border-left: 5px solid #d9534f; background-color: #fdf7f7; }");
        sb.AppendLine(".severity-MEDIUM { border-left: 5px solid #f0ad4e; background-color: #fcf8e3; }");
        sb.AppendLine(".severity-LOW { border-left: 5px solid #5bc0de; background-color: #f4f8fa; }");
        sb.AppendLine(".header { background-color: #0078d4; color: white; padding: 15px; margin-bottom: 20px; }");
        sb.AppendLine("</style></head><body>");
        
        sb.AppendLine($"<div class='header'><h2>Drift Detected: {pipelineName}</h2></div>");
        sb.AppendLine($"<p>Drift analysis has detected <strong>{driftRecords.Count()}</strong> discrepancies between your Infrastructure as Code definitions and the actual Azure resources.</p>");
        
        foreach (var drift in driftRecords.OrderByDescending(d => d.Severity))
        {
            var severityClass = $"severity-{drift.Severity?.ToUpper() ?? "LOW"}";
            
            sb.AppendLine($"<div class='drift-item {severityClass}'>");
            sb.AppendLine($"<h3>[{drift.Severity}] {drift.ResourceType}: {drift.ResourceName}</h3>");
            sb.AppendLine($"<p><strong>Property:</strong> {drift.Property}</p>");
            sb.AppendLine($"<p><strong>Actual:</strong> <code>{drift.ActualValue}</code></p>");
            sb.AppendLine($"<p><strong>Expected (IaC):</strong> <code>{drift.ExpectedValue}</code></p>");
            
            if (!string.IsNullOrEmpty(drift.Description))
                sb.AppendLine($"<p><em>{drift.Description}</em></p>");
                
            sb.AppendLine("</div>");
        }
        
        sb.AppendLine("<p><small>Generated by Chivato Drift Monitor</small></p>");
        sb.AppendLine("</body></html>");
        
        return sb.ToString();
    }

    private string GenerateDriftReportPlainText(string pipelineName, IEnumerable<DriftRecordEntity> driftRecords)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"DRIFT DETECTED: {pipelineName}");
        sb.AppendLine(new string('=', 30));
        sb.AppendLine($"Found {driftRecords.Count()} discrepancies.");
        sb.AppendLine();

        foreach (var drift in driftRecords.OrderByDescending(d => d.Severity))
        {
            sb.AppendLine($"[{drift.Severity}] {drift.ResourceType}: {drift.ResourceName}");
            sb.AppendLine($"Property: {drift.Property}");
            sb.AppendLine($"Actual: {drift.ActualValue}");
            sb.AppendLine($"Expected: {drift.ExpectedValue}");
            sb.AppendLine(new string('-', 20));
        }

        return sb.ToString();
    }

    public async Task SendCredentialExpirationWarningAsync(
        IEnumerable<string> recipients,
        IEnumerable<CredentialStatus> expiringCredentials,
        CancellationToken cancellationToken = default)
    {
        if (!recipients.Any()) return;

        // Implementation stub - In a real scenario, this would send an email similar to the drift report
        _logger.LogInformation("Simulating sending credential expiration warning to {Count} recipients", recipients.Count());
        await Task.CompletedTask;
    }

    public async Task<bool> TestConnectionAsync(string connectionString, string fromEmail)
    {
        try
        {
            var client = new EmailClient(connectionString);
            // Just verifying we can create the client. To really test, we might need to send a dummy email?
            // But usually validation happens on send. 
            // We can assume valid if connection string format is OK. 
            // A more robust check would try to list operations or something if permissions allow, 
            // but Azure Communication Services is send-centric.
            
            return await Task.FromResult(true);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Email connection test failed");
            return false;
        }
    }
}
